spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
app:
  topics:
    sms-consumer: sms_message_send
twilio:
  ACCOUNT_SID: ${ACCOUNT_SID}
  AUTH_TOKEN: ${AUTH_TOKEN}
  TWILIO_PHONE: ${TWILIO_PHONE}
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG
